version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app:cached
      # Python 캐시 디렉토리 제외
      - /app/__pycache__
      - /app/app/__pycache__
      - /app/app/data/__pycache__
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    # 잘못된 옵션 제거하고 올바른 uvicorn 옵션만 사용
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload --log-level warning
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # 볼륨 마운트 활성화 - 개발 편의성 향상
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/public:/app/public:cached
      - ./frontend/config-overrides.js:/app/config-overrides.js:cached
      - ./frontend/package.json:/app/package.json:cached
      - ./frontend/.env:/app/.env:cached
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - GENERATE_SOURCEMAP=false
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - FAST_REFRESH=false
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - PORT=3001
      # 실제 유효한 토큰으로 변경하세요 (https://developer.webex.com/docs/getting-started에서 발급)
      - REACT_APP_WEBEX_ACCESS_TOKEN=MTVlYjFhNTAtMWViYy00MGQ3LWE3YTgtNzc4YjNjZWUwNzg2MjNhY2UxNDItMTQw_P0A1_4afba7eb-aa79-414b-83ef-005e438f3e44
    depends_on:
      - backend
