version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: songkok-device-backend
    ports:
      - "8001:8001"  # 호스트 및 컨테이너의 8001 포트를 사용
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - device-network
    environment:
      - PORT=8001  # 백엔드 서버 포트 설정
      - ADMIN_SERVER_URL=http://host.docker.internal:8000  # 환경 변수로 관리자 서버 URL 설정
    # host.docker.internal을 지원하기 위한 설정 추가
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: songkok-device-frontend
    ports:
      - "3001:80"  # 호스트의 3001 포트와 컨테이너의 80 포트 매핑
    restart: always
    networks:
      - device-network
    environment:
      - BACKEND_URL=http://backend:8001  # 백엔드 서비스 URL 환경 변수 설정

networks:
  device-network:
    driver: bridge